StarKitchenApi/Controllers/AdminController.cs
using StarKitchenApi.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarKitchenApi.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        DatabaseCredential dbC = new DatabaseCredential();
        public ActionResult adminEnter()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AdminDetail(AdminCredential user)
        {
            //Pass the data to store the record into the table 

            DataTable tbl = new DataTable();
            tbl = dbC.CheckLogin("select * from AdminCredential where UserDetail='" + user.UserDetail + "'and PasswordDetail='" + user.PasswordDetail + "'");

            if (tbl.Rows.Count > 0)
            {
                return View("AdminZone");
            }
            else
            {
                return View("invalid");
            }
        }
        public ActionResult AdminZone()
        {
            ViewBag.Title = "Home Page";

            return View();
        }

        public ActionResult Invalid()
        {
            ViewBag.Title = "Home Page";

            return View();
        }

        // GET: Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

StarKitchenApi/Controllers/ServiceController.cs
using StarKitchenApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarKitchenApi.Controllers
{
    public class ServiceController : Controller
    {
        // GET: Service

        StarKitchenEntities dbc = new StarKitchenEntities();
        public ActionResult ViewSevice()
        {
            return View(dbc.ServicesCredentials.ToList());
        }


        public ActionResult SeviceCorner()
        {
            return View(dbc.ServicesCredentials.ToList());
        }


        // GET: Client/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Client/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Client/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "id")]ServicesCredential services)
        {
            if (!ModelState.IsValid)
                return View();
            dbc.ServicesCredentials.Add(services);
            dbc.SaveChanges();
            return RedirectToAction("ViewService");
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int id)
        {
            var IdToEdit = (from m in dbc.ServicesCredentials where m.id == id select m).First();
            return View(IdToEdit);
        }

        // POST: Client/Edit/5
        [HttpPost]
        public ActionResult Edit(ServicesCredential IdToEdit)
        {
            var orignalRecord = (from m in dbc.ServicesCredentials where m.id == IdToEdit.id select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            dbc.Entry(orignalRecord).CurrentValues.SetValues(IdToEdit);

            dbc.SaveChanges();
            return RedirectToAction("ViewService");


        }

        // GET: Client/Delete/5
        public ActionResult Delete(ServicesCredential IdToRemove)
        {
            var d = dbc.ServicesCredentials.Where(x => x.id == IdToRemove.id).FirstOrDefault();
            dbc.ServicesCredentials.Remove(d);
            dbc.SaveChanges();
            return RedirectToAction("ViewService");
        }

        // POST: Service/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

StarKitchenApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />

    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--js-->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <!--js-->
    <!--webfonts-->
    <link href='//fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <!--webfonts-->
    <script src="~/js/responsiveslides.min.js"></script>
    <script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
    </script>
    <script src="~/js/easyResponsiveTabs.js" type="text/javascript"></script>
    <script type="text/javascript">
			    $(document).ready(function () {
			        $('#horizontalTab,#horizontalTab1,#horizontalTab2').easyResponsiveTabs({
			            type: 'default', //Types: default, vertical, accordion
			            width: 'auto', //auto or any width like 600px
			            fit: true   // 100% fit in a container
			        });
			    });
    </script>




</head>
<body>
    <!--header-->
    <div class="header" id="home">
        <div class="header-top">
            <div class="container">
                <div class="logo">
                    <h1><a href="@Url.Action("adminEnter","Admin")">Star Kitchen</a></h1>
                </div>
                <div class="social-icons">
                    <a href="#"><i class="icon"></i></a>
                    <a href="#"><i class="icon1"></i></a>
                    <a href="#"><i class="icon2"></i></a>
                    <a href="#"><i class="icon3"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="container">
            <div class="header-bottom">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <nav class="menu menu--francisco">
                                <ul class="nav navbar-nav menu__list">
                                    <li class="menu__item menu__item--current"><a href="@Url.Action("Index","Home")" class="menu__link"><span class="menu__helper">Home</span></a></li>
                                    <li class="menu__item"><a href="@Url.Action("About","Home")" class="menu__link"><span class="menu__helper">About</span></a></li>
                                    <li class="menu__item"><a href="@Url.Action("ServiceCorner","Service")" class="menu__link"><span class="menu__helper">Services</span></a></li>
                                    <li class="menu__item"><a href="@Url.Action("adminEnter","Admin")" class="menu__link"><span class="menu__helper">Login</span></a></li>
                                    <li class="menu__item"><a href="@Url.Action("Gallery","Home")" class="menu__link"><span class="menu__helper">Gallery</span></a></li>
                                    <li class="menu__item"><a href="@Url.Action("mailUs","Home")" class="menu__link"><span class="menu__helper">Mail Us</span></a></li>
                                </ul>
                            </nav>

                        </div><!-- /.navbar-collapse -->
                        <!-- /.container-fluid -->
                    </div>
                </nav>

            </div>
        </div>
    </div>
    <!--header-->
    <!--banner-->
    <div class="demo-2">
        <div id="example2" class="core-slider core-slider__carousel example_2">
            <div class="core-slider_viewport">
                <div class="core-slider_list">
                    <div class="core-slider_item">
                        <img src="~/images/ba3.jpg" class="img-responsive" alt="">
                    </div>
                    <div class="core-slider_item">
                        <img src="~/images/ba1.jpg" class="img-responsive" alt="">
                    </div>
                    <div class="core-slider_item">
                        <img src="~/images/ba2.jpg" class="img-responsive" alt="">
                    </div>
                    <div class="core-slider_item">
                        <img src="~/images/ba3.jpg" class="img-responsive" alt="">
                    </div>
                </div>
            </div>
            <div class="core-slider_nav">
                <div class="core-slider_arrow core-slider_arrow__right"></div>
                <div class="core-slider_arrow core-slider_arrow__left"></div>
            </div>
            <div class="core-slider_control-nav"></div>
        </div>
    </div>
    <link href="~/css/coreSlider.css" rel="stylesheet" type="text/css">
    <script src="~/js/coreSlider.js"></script>

    <script>
        $('#example1').coreSlider({
            pauseOnHover: false,
            interval: 3000,
            controlNavEnabled: true
        });
        $('#example2').coreSlider({
            clone: true,
            cloneItems: 3
        });
    </script>
    <!--banner-->


    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
    </div>


    <!--footer-->
    <div class="footer-w3l">
        <div class="container">
            <div class="footer-grids">
                <div class="col-md-4 footer-grid">
                    <h4>Get In Touch</h4>
                    <p>Get Star Kitchen Festive & other offers on Email ID, Enter your Email Id in the Box. You can also Contact us by Entering your details at Contact us paage, we will review your Query and Contact you.</p>
                </div>
                <div class="col-md-4 footer-grid">
                    <h4>Subscribe For Best Offers</h4>
                    <form action="#" method="post">
                        <input type="text" name="email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
                        <input type="submit" value="Subscribe">
                    </form>
                </div>
                <div class="col-md-4 footer-grid">
                    <h4>Address</h4>
                    <p>
                        SCO 95, Dera Road <br>
                        Phase 9, Batala || Punjab<br>
                        Telephone: +91 01871-69212<br>
                        Mobile: +91 78149-76999<br>

                    <p>E-mail : <a href="mailto:info@example.com">bunty@starkitchen.com</a></p>

                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!--footer-->
    <!--copy-->
    <div class="copy-section">
        <div class="container">
            <div class="footer-top">
                <p>© 2020 Star Kitchen. All rights reserved | Developed by <a href="http://pearlinstitute.in">Pearl Institute</a></p>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>